/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UploadMessage implements org.apache.thrift.TEnum {
  BEGIN_UPLOAD(0),
  PROGRESS_UPLOAD(1),
  END_UPLOAD(2);

  private final int value;

  private UploadMessage(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UploadMessage findByValue(int value) { 
    switch (value) {
      case 0:
        return BEGIN_UPLOAD;
      case 1:
        return PROGRESS_UPLOAD;
      case 2:
        return END_UPLOAD;
      default:
        return null;
    }
  }
}
